### ISSUE TITLE
Improve the README.md documentation

### ISSUE THREAD

**Issue by osipov** [IBM-MIL/IBM-Ready-App-for-Banking#1]
The [38f892c](https://github.com/IBM-MIL/IBM-Ready-App-for-Banking/blob/38f892ce47eb02164d6b16e8959ec7959416f8ff/README.md) version of the documentation is hard to use. Would like to see a click to deploy to bluemix button and additional detail around the mobile portion of the app.

**Comment by kweinmeister** [comment]
Thanks for the feedback. I would suggest another issue to track the "click to deploy to BlueMix" enhancement. About the docs, can you provide any specifics on what details and/or clarifications you'd like to see?

**Comment by osipov** [comment]
Hi Karl. The specific concern is with level of detail in the documentation, for example lack of cf CLI commands to create and configure services in Bluemix. Unfortunately we don't have a best practices/styleguide type of a document for the README, but I encourage you to take a look at documentation from Jeff Sloyer https://github.com/IBM-Bluemix/box-watson and other folks from the developer outreach team. They are continuously on the lookout for how the github developer community does documentation and might be able to give you more specific pointers. It would be a good idea to setup some time to conf. call with developer advocates from the IBM-Bluemix org on github and as them to peer review the README file.

**Comment by kweinmeister** [comment]
The README is a small sliver of the docs. Did you have a chance to go review all of the full documentation linked from the bottom of the README?

**Comment by osipov** [comment]
Just briefly -- I went to the link, tried the Start pull down and there was something about the design language. Wasn't sure how to proceed and bailed.

**Comment by kweinmeister** [comment]
Fixed with commit 1790f06e72050cc108fcfcfb64f34189c7ed1b49
