### ISSUE TITLE
The recurring payment is not consistent between the summary page and the edit page of a goal for the pre populated goals and a newly added goal

### ISSUE THREAD

**Issue by dfirsht** [IBM-MIL/IBM-Ready-App-for-Banking#5]
<img width="376" alt="screen shot 2015-10-02 at 4 30 37 pm" src="https://cloud.githubusercontent.com/assets/5191832/10258381/517eed06-6923-11e5-9fcd-a6951f8b6c4d.png">
<img width="373" alt="screen shot 2015-10-02 at 4 33 39 pm" src="https://cloud.githubusercontent.com/assets/5191832/10258411/8d1859b0-6923-11e5-9fca-744cba71af6b.png">

These two images were taken one after another without any editing of values

**Comment by sccheng** [comment]
Pre populated goals and newly added goals will have matching recurring payments between the summary and edit goal pages.

However, recurring payments are still inconsistent between the summary and edit pages if you have edited the goal. Will open a new issue for this.
