### ISSUE TITLE
Misaligned text in Add Goal Completion screen

### ISSUE THREAD

**Issue by dfirsht** [IBM-MIL/IBM-Ready-App-for-Banking#7]
Steps to reproduce:  Add goal > More Options > select option > this screen
![img_0034](https://cloud.githubusercontent.com/assets/5191832/10436820/84bcd688-70ee-11e5-87e9-aed91d590166.PNG)

**Comment by sccheng** [comment]
Closing this issue, as we are unable to reproduce it.
