### ISSUE TITLE
Source code formatting showing up in Add Goal options

### ISSUE THREAD

**Issue by dfirsht** [IBM-MIL/IBM-Ready-App-for-Banking#8]
Steps to reproduce: Add goal > More Options > this screen
![img_0032](https://cloud.githubusercontent.com/assets/5191832/10436855/c4b6a48a-70ee-11e5-8bc8-3fb3d6c620cc.PNG)

**Comment by sccheng** [comment]
Closing this issue, since we are unable to reproduce it.
